### ISSUE TITLE
Edimax EW-7822UMX (802.11ax USB) 7392:6822

### ISSUE THREAD

**Issue by openMolNike** [lwfinger/rtl8852bu#4]
Hi. Sorry for my bad english.

I have bought Edimax EW-7822UMX (802.11ax USB adapter) because I want Wi-fi 6 speed.
It works on windows (my speed is 70-90 Mbytes/s) and should work on linux with old kernels.

Here are old drivers:
https://www.edimax.com/edimax/download/download/data/edimax/global/download/wireless_adapter_ax1800/ew-7822umx
Need kernel before 5.11 =( Can't downgrade my linux without reinstall =(

lsusb output:
Bus 003 Device 002: ID 7392:6822 Edimax Technology Co., Ltd 802.11ax WLAN Adapter

I've searched "7392:6822" of that driver and found here 
https://deviceinbox.com/drivers/2025-realtek-wifi-driver-5001-0-15-110.html
So I think it has 8832BU or 8852BU chipset

I'm not a developer but I maked it work by this driver. I just tried to edit it for luck.
I've edited this files to make this device visible for your driver:

1)usb_intf.c
#define USB_VENDER_ID_EDIMAX		0x7392
	{USB_DEVICE_AND_INTERFACE_INFO(USB_VENDER_ID_EDIMAX, 0x6822, 0xff, 0xff, 0xff), .driver_info = RTL8852B},

2)8852bu.mod.c
MODULE_ALIAS("usb:v7392p6822d*dc*dsc*dp*icFFiscFFipFFin*");

And it works!! But it works too slow (20 Mbytes/s). Much slower then same device on windows (80 Mbytes/s).
There is no point in using it like this. My old wifi-5 adapter is faster(38 Mbytes/s).

What else I can do?

**Comment by openMolNike** [comment]
I tried also:
1) RTL8852BP and RTL8832BR instead of RTL8852B - not working
2) turning off the built-in module to eliminate interference - no effect on speed
sudo ip link set wlo1 down

**Comment by openMolNike** [comment]
Ok... I I bought another adapter "TP-LINK Archer TX20UH"
This apadter works with this https://github.com/lwfinger/rtl8852au without any addtionas changes.
But same problem! 20-23 Mbytes/s 
What the hell? Are this drivers finished or I have problems with USB port?

**Comment by lwfinger** [comment]
I do not have an rtw8852bu, but I have an rtw8852cu. With it, connecting to a wifi6 router over a 5 GHz connection, I got roughly 350 Mbps (44 MBps) rates using a local LibreSpeed server.

These drivers are the ones the vendor provides for internal testing, but are released. hey are far from polished.
The rtw89 drivers in the kernel have the hooks for USB drivers, but no one has yet written them. On PCIe interfaces, those devices get about 750 Mbps.

At this point, there is not much more that I can offer. The devicees could go faster, but not with the current drivers.
