### ISSUE TITLE
fails to build on rpi4 arm64

### ISSUE THREAD

**Issue by abn0mad** [lwfinger/rtl8852bu#5]
First off, thanks for all the hard work on creating and maintaining these driver solutions :)

I have an Asus USB-NANO-AX55:

`ID 0b05:1a62 ASUSTek Computer, Inc. 802.11ax WLAN Adapter`

Device: Raspberry Pi 4
OS: Raspberry Pi OS 64-bit

For which I initially tried to build your [rtl8852au](https://github.com/lwfinger/rtl8852au) driver. After the device did not seem to enumerate, I stumbled across this [solution](https://github.com/lwfinger/rtl8852au/issues/54).

After cloning the repo, I first got:

`sudo dkms add .\
Error! Arguments <module> and <module-version> are not specified\
Usage: add <module>/<module-version> or\
       add -m <module>/<module-version> or\
       add -m <module> -v <module-version>\`

I then copied and modified dkms.conf from your rtl8852au repo, after which I get with both `dkms install` and regular `make`:

`sudo dkms build rtl8852bu -v 1.15.0.1\
\
Kernel preparation unnecessary for this kernel.  Skipping...\
\
Building module:\
cleaning build area...\
'make' -j4 KVER=6.1.21-v8+...(bad exit status: 2)\
Error! Bad return status for module build on kernel: 6.1.21-v8+ (aarch64)\
Consult /var/lib/dkms/rtl8852bu/1.15.0.1/build/make.log for more information.`

Which says:

`cat /var/lib/dkms/rtl8852bu/1.15.0.1/build/make.log\
DKMS make.log for rtl8852bu-1.15.0.1 for kernel 6.1.21-v8+ (aarch64)\
Tue  3 Oct 16:49:58 HKT 2023\
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/6.1.21-v8+/build M=/var/lib/dkms/rtl8852bu/1.15.0.1/build  modules \
make[1]: Entering directory '/usr/src/linux-headers-6.1.21-v8+'\
Makefile:775: arch/aarch64/Makefile: No such file or directory\
make[1]: *** No rule to make target 'arch/aarch64/Makefile'.  Stop.\
make[1]: Leaving directory '/usr/src/linux-headers-6.1.21-v8+'\
make: *** [Makefile:729: modules] Error 2\`

I assume then that this repo does not yet have the fixes applied to it that the 8852au repo has? 

(apologies on the large number of backslashes, line breaks weren't cooperating)

**Comment by lwfinger** [comment]
I added the modifications that allow arm64 platforms to build. That should be OK now.
