### ISSUE TITLE
make: *** No rule to make target 'sign-install'.  Stop.

### ISSUE THREAD

**Issue by XRayA4T** [lwfinger/rtl8852bu#7]
Thanks for your hard work.

I'm trying to install on Ubuntu 23.10 using :+1: git clone git://github.com/lwfinger/rtl8852bu.git
cd rtl8852bu
make
sudo make sign-install

But I get make: *** No rule to make target 'sign-install'.  Stop.

**Comment by lwfinger** [comment]
The vendor drivers have never supported secure boot. I have added that part to the Makefile, but you will need to be carefull about handling the MOK bluescreen that will happen on the next reboot. Do a 'git pull' and you will be able to sign the module.
